documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"
          - ".github/**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package-lock.json"
          - "package.json"
          - "pyproject.toml"
          - "requirements*.txt"
          - "poetry.lock"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "test/**"
          - "tests/**"
          - "**/*.test.*"
          - "**/*.spec.*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "lib/**"
          - "bin/**"
